eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8763/eureka/
server:
  port: 8766

spring:
  application:
    name: service-feign
  ##zipkin 配置 独立运行的服务器
  zipkin:
    base-url: http://127.0.0.1:9411
    sender:
      type: rabbit
  sleuth:
    sampler:
      probability: 1.0
    ##rabbitmq
    rabbitmq:
      username: admin
      password: admin
      host: 127.0.0.1
      port: 5672
